# Site settings
title: Corsarios Creativos
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Corsarios Creativos
user_description: Somo un estudio especializado en trabajos de creatividad que requieren de un nivel técnico alto. Nos apasiona la fusión entre la tecnología y el diseño. 
user_title: Creative Software Developers
email: ok@corsarioscreativos.es
twitter_username: corsarios_
github_username:  corsarios
instagram_username:  corsarioscreativos
vimeo_username: corsarios

collections:
  proyects:
    output: true
    permalink: /:collection/:name
  
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
